@startuml

activate ControllerDragDrop
ControllerDragDrop -> ModelUML : annalyseFichier
activate ModelUML
create Analyser
ModelUML -> Analyser : new
activate Analyser
Analyser --> ModelUML
deactivate Analyser
ModelUML -> Analyser : analyse
activate Analyser
create Classe
Analyser -> Classe : new
activate Classe
Classe --> Analyser
deactivate Classe
Analyser -> Analyser : getParameterTypeNames
activate Analyser
Analyser --> Analyser
deactivate Analyser
Analyser -> Analyser : getParameterTypeNames
activate Analyser
Analyser --> Analyser
deactivate Analyser
Analyser --> ModelUML
deactivate Analyser
ModelUML -> ModelUML : ajouterClasse
activate ModelUML
ModelUML --> ModelUML
deactivate ModelUML
ModelUML -> Classe : UMLString
activate Classe
Classe -> Classe : getUMLVisibility
activate Classe
Classe --> Classe
deactivate Classe
Classe -> Classe : getUMLVisibility
activate Classe
Classe --> Classe
deactivate Classe
Classe -> Classe : getUMLVisibility
activate Classe
Classe --> Classe
deactivate Classe
Classe --> ModelUML
deactivate Classe
ModelUML -> ModelUML : notifierObservateurs
activate ModelUML
ModelUML -> Observateur : actualiser
activate Observateur
Observateur --> ModelUML
deactivate Observateur
ModelUML --> ModelUML
deactivate ModelUML
return
@enduml